- alias: Open covers morning
  trigger:
    # Prefix the first line of each trigger configuration
    # with a '-' to enter multiple
    - platform: sun
      event: sunrise
      offset: '0:30:00'
  condition:
    # Prefix the first line of each condition configuration
    # with a '-'' to enter multiple
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    service: cover.set_cover_position
    data:
      entity_id: group.livingroom_covers
      position: 70

- alias: Turn on outside lights at dusk
  trigger:
    # Prefix the first line of each trigger configuration
    # with a '-' to enter multiple
    platform: sun
      event: sunset
      offset: '0:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.relaybutton_5_1

- alias: Turn off outside lights at dawn
  trigger:
    # Prefix the first line of each trigger configuration
    # with a '-' to enter multiple
    platform: sun
      event: sunrise
      offset: '-0:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.relaybutton_5_1

- alias: Turn off outside lights if its daylight
  trigger:
    # Prefix the first line of each trigger configuration
    # with a '-' to enter multiple
    platform: state
      entity_id: group.outside_lights
      to: 'on'
  condition:
    # Prefix the first line of each condition configuration
    # with a '-'' to enter multiple
    condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    service: switch.turn_off
    entity_id: group.outside_lights
