# - alias: Open covers morning
  # trigger:
  # - platform: sun
    # event: sunrise
    # offset: 0:30:00
  # condition:
  # - condition: time
    # weekday:
    # - sun
    # - mon
    # - tue
    # - wed
    # - thu
  # - condition: state
    # entity_id: group.all_devices
    # state: home
  # action:
    # service: cover.set_cover_position
    # data:
      # entity_id: group.all_covers
      # position: 70
- action:
  - data:
      entity_id: switch.relaybutton_5_0
    service: switch.turn_on
  alias: Turn outside lights on at sunset
  condition: []
  id: '1503673603735'
  trigger:
  - event: sunset
    offset: 00:00:00
    platform: sun
- action:
  - data:
      entity_id: switch.relaybutton_5_0
    service: switch.turn_off
  alias: Turn outside lights off at sunrise
  condition: []
  id: '1503673697244'
  trigger:
  - event: sunrise
    offset: 00:00:00
    platform: sun
- action:
  - data:
      entity_id: group.all_covers
      position: 70
    service: cover.set_cover_position
  alias: Open covers at sunrise
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  - condition: template
    value_template: '{% if now().weekday() in [0,1,2,3,7] %}

      true

      {%else%}

      false

      {%endif%}'
  id: '1503754027336'
  trigger:
  - event: sunrise
    offset: +00:30:00
    platform: sun
